/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export { }

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    Block: typeof import('./components/Block.vue')['default']
    Chain: typeof import('./components/chain/Chain.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InteropRequest: typeof import('./components/InteropRequest.vue')['default']
    Registry: typeof import('./components/chain/Registry.vue')['default']
    RequestList: typeof import('./components/RequestList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubmitInteropTxButton: typeof import('./components/buttons/SubmitInteropTxButton.vue')['default']
  }
}
